=== AndresTcharro/TrabajoLibreXML/tienda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Elemeto Padre que contien a biblioteca con su atributo -->
<!-- ............................................................................................. -->
<xs:element name="tienda">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="biblioteca" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="NIF" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

<!-- Hijo de tiendad que asu vez contiene un total de 5 elemento, dos de los cuales son hijos(libros, clientes) -->
<!-- .......................................................................................................... -->
<xs:element name="biblioteca" >
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="company" type="xs:string"/>
            <xs:element name="url">
                <xs:simpleType>
                    <xs:restriction base="xs:string" >
                        <xs:pattern value="[www]{3}\.[a-z0-9]{2,}\.[A-Za-z]{2,}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <!-- llamamos a su hijos con "ref="" -->
            <xs:element ref="libros"/>
            <xs:element ref="clientes"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>



<!-- Libros perteneciente a biblioteca, el elemento libro con mínimo y máximo de ocurrencias  -->
<!-- ........................................................................................................ -->
<xs:element name="libros">
    <xs:complexType>
        <xs:sequence>
            <!-- como minimo queremos que exista un libro y no tenemos lmite en el máximo -->
            <xs:element ref="libro" minOccurs="1" maxOccurs="unbounded"/> 
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- Clientes perteneciente a biblioteca, el elemento libro con mínimo y máximo de ocurrencias  -->
<!-- ........................................................................................................ -->
<xs:element name="clientes">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="cliente" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
    

                
<!-- Libro contiene varios elementos complejos que asu vez contienen elementos simples  -->
<!-- ......................................................................................................... -->
<xs:element name="libro">
<xs:complexType>
        <xs:sequence>

<xs:element name="nombre" type="xs:string"/>
<xs:element name="codigo">
    <xs:simpleType>
        <xs:restriction base="xs:string">
            <!-- restriccion de codigo 3 letras, 4 numeros, y 1 simbolo no alfanumerico  -->
            <xs:pattern value="[A-Za-z]{3}[0-9]{4}[^A-Za-z0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType> 
</xs:element>
<!-- en el tipo lo declaramos en "date" lo cual nos indicara que metamos segun este orden año,mes,día -->
<xs:element name="fecha" type="xs:date"/>
<!-- indicamos que el valor del precio solo puede contener un total de 2 digitos de fracccion  -->
<!-- y un total de 4 numeros  -->
<xs:element name="precio">
    <xs:simpleType>
        <xs:restriction base="xs:decimal">
                <xs:fractionDigits value="2"/>
                <xs:totalDigits value=" 4"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<xs:element name="categoria">
    <xs:simpleType>
<!-- En la etiqueta categoria le indicamos que solo queremos que sean posibles entres estas tres opciones -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ficción"/>
            <xs:enumeration value="Terror"/>
            <xs:enumeration value="Infantil"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<!-- En este caso indicamos que el type del atributo es un int con un valor 45 como fijo -->
<xs:element name="unidadesDisponibles" type="xs:int" fixed="45"/>
</xs:sequence>
<!-- atributi al cual le indicamos que puede o no aparecer pero si aparece tiene que aparecer con el numero 2 que le indicamos -->
<xs:attribute name="id" type="xs:int" />
</xs:complexType>
</xs:element>

<!-- Cliente contiene varios elementos complejos que asu vez contienen elementos simples  -->
<!-- ......................................................................................................... -->

<xs:element name="cliente">
    <xs:complexType>
        <xs:sequence>
<xs:element name="nombre" type="xs:string"/>
<xs:element name="codigo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
<!-- restriccion de codigo 3 letras, 4 numeros, y 1 simbolo no alfanumerico  -->
            <xs:pattern value="[A-Za-z]{3}[0-9]{4}[^A-Za-z0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType> 
</xs:element>
            <!-- en el tipo lo declaramos en "date" lo cual nos indicara que metamos segun este orden año,mes,día -->
<xs:element name="fecha" type="xs:date"/>

<xs:element name="apellidos">
    <xs:complexType>
<!-- con la etiqueta choice le indicamos que queremos uno de estos dos apellidos  -->
        <xs:choice>
            <xs:element name="primerapellido" type="xs:string"/>
            <xs:element name="segundoapellido" type="xs:string"/>
        </xs:choice>
    </xs:complexType>
</xs:element>
<xs:element name="edad">
    <xs:simpleType>
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="18"/>
            <xs:maxExclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<!-- aplicamos un restricion al email -->
<xs:element name="email">
    <xs:simpleType>
        <xs:restriction base="xs:string" >
            <xs:pattern value="[A-Za-z0-9]*@+[A-Za-z0-9-]*.[A-Za-z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<xs:element name="telefono">
    <xs:simpleType>
        <xs:restriction base="xs:string">
<!-- queremos 3 numeros que se encuentren dentro del parentesis prresedidos de el signo + -->
<!-- y que contenga 9 numeros  -->
            <xs:pattern value="\(\+[0-9]{3}\)[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
<xs:element name="direccion">
    <xs:simpleType>
        <xs:restriction base="xs:string">
<!--indicamos como debemos tratar los espacios en blanco, tabulaciones, los saltos de línea-->
<!-- otras opciones: -->
<!-- replace -> sustituye todas las tabulaciones por espacios en blanco -->
<!-- collapse-> los espacios en blanco eliminarlos y los varios espacios en blanco por un unico -->
            <xs:whiteSpace value="preserve"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>


<!-- Cierre del elemento tienda y el schema -->
</xs:sequence>
<!-- le indicamos que el atributo es obligatorio que lo indiquemos /podemos obtar por la optional  -->
<xs:attribute name="identificador" type="xs:string" use="required"  />
</xs:complexType>
</xs:element>

<!-- ........................................................................................................... -->
</xs:schema>  
<!-- ..............................................Fin........................................ -->
<!-- Cristina he dejado comentado la etiqueta "datos_comun" ya que era la que contenia mis elementos 
"nombre" ," codigo", "fecha" tanto para cliente como para libro, el problema que me surgio era que queria encapsular 
estos tres elementos dentro de la etiqueta , lo que me daba un proble en el XSL donde al poner la ruta no habia forma que 
me mostra ya que solo lograba o poner la ruta ->"select="//libro" la que me mostraba todos los elemnteos 
, lo que pasaba era que "datos en comun" me mostraba en una sola celda -> logre que me mostra el contenido pero 
esto implicaba que la ruta tenia que cambiar ->select="//libro/datos_comun" , esto me mostraba los tres elementos 
que contenia este pero no me lograba mostrar el resto del contenido de libro. Mi opción fue quitar la etiqueta de 
"datos_comun" y llamar a cada elemento individualmente  eso si para evitar las muñecas rusas , deje 
creado el "TYPE=datos:basicos" el cual se lo pase a cada elemento básico-->

=== AndresTcharro/TrabajoLibreXML/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="tienda.xslt" type="text/xsl"?>
<tienda NIF="A -3900001- 3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./tienda.xsd">
<biblioteca>
    <nombre>Biblioteca X</nombre>
    <company>Biblioteca S.L </company>
    <url>www.biblioteca.com</url>

<libros>
    <!-- el id lo declaramos como un atributo USE EL  -->
    <!-- que puede aparecer o no pero si aparece tiene que tener el id indicado -->
    <libro id="2">
        <!-- <datos_comun> -->
            <nombre>Halloween</nombre>
        <!-- Formato que inventado 4 numeros y 2 simbolos no alfanumericos -->
            <codigo>BBB0001$%</codigo>
        <!-- formato fecha -->
            <fecha>2002-09-24</fecha>
        <!-- </datos_comun> -->
        <!-- formato precio -->
        <precio>12.99</precio>
        <!--Tenemos que elegir entre tres categorias -->
        <categoria>Terror</categoria>
        <!-- nos indica el numero de unidades disponibles -->
        <unidadesDisponibles>45</unidadesDisponibles>
    </libro>   
    <libro id="3">
        <!-- <datos_comun> -->
            <nombre>Pesadilla en Elm Street</nombre>
        <!-- Formato que inventado 4 numeros y 2 simbolos no alfanumericos -->
            <codigo>AAA0002#$</codigo>
        <!-- formato fecha -->
            <fecha>1984-10-31</fecha>
        <!-- </datos_comun> -->
        <!-- formato precio -->
        <precio>16.99</precio>
        <!--Tenemos que elegir entre tres categorias -->
        <categoria>Terror</categoria>
        <!-- nos indica el numero de unidades disponibles -->
        <unidadesDisponibles>45</unidadesDisponibles>
    </libro>
    <libro id="4">
        <!-- <datos_comun> -->
            <nombre>El juego de Ender</nombre>
        <!-- Formato que inventado 4 numeros y 2 simbolos no alfanumericos -->
            <codigo>JJJ0003$€</codigo>
        <!-- formato precio -->
            <fecha>1985-09-24</fecha>
        <!-- </datos_comun> -->
        <precio>10.40</precio>
        <!-- formato fecha -->
        <!--Tenemos que elegir entre tres categorias -->
        <categoria>Ficción</categoria>
        <!-- nos indica el numero de unidades disponibles -->
        <unidadesDisponibles>45</unidadesDisponibles>
    </libro>
    <libro id="5">
        <!-- <datos_comun> -->
            <nombre>la ovejita que vino a cenar </nombre>
        <!-- Formato que inventado 4 numeros y 2 simbolos no alfanumericos -->
            <codigo>MSN0010$$</codigo>
        <!-- formato fecha -->
            <fecha>2006-08-07</fecha>
        <!-- </datos_comun> -->
        <!-- formato precio -->
        <precio>15.22</precio>
        <!--Tenemos que elegir entre tres categorias -->
        <categoria>Infantil</categoria>
        <!-- nos indica el numero de unidades disponibles -->
        <unidadesDisponibles>45</unidadesDisponibles>
    </libro>
</libros>
<clientes>
    <cliente identificador="A">
        <!-- <datos_comun> -->
            <nombre>Juan</nombre>
        <!-- Formato 3 letras, 4 numeros, 1 simoblo -->
            <codigo>Fab3456#$</codigo>
            <fecha>2022-05-20</fecha>
            <!-- </datos_comun> -->
        <apellidos>
            <!-- solo podemos elegir entre el primer apellido o el segundo  -->
            <!-- <primerapellido>Snchaez</primerapellido> -->
            <segundoapellido>Pérez</segundoapellido>
        </apellidos>
        <!-- restringimimos la edad entre los 18 años a los 100 años y solo valores posistivos-->
        <edad>25</edad>
        <email>Ejempl12@gmail.com</email>
        <telefono>(+034)695040750</telefono>
        <direccion>calle sin número</direccion>
    </cliente>
    <cliente identificador="B">
        <!-- <datos_comun> -->
            <nombre>Juan</nombre>
        <!-- Formato 3 letras, 4 numeros, 1 simoblo -->
            <codigo>Fab3456#%</codigo>
            <fecha>2022-05-20</fecha>
        <!-- </datos_comun> -->
        <apellidos>
            <!-- solo podemos elegir entre el primer apellido o el segundo  -->
            <primerapellido>Snchaez</primerapellido>
            <!-- <segundoapellido>Pérez</segundoapellido> -->
        </apellidos>
        <!-- restringimimos la edad entre los 18 años a los 100 años y solo valores posistivos-->
        <edad>27</edad>
        <email>Ejempl12@gmail.com</email>
        <telefono>(+034)695040750</telefono>
        <direccion>calle sin número</direccion>
    </cliente>
    <cliente identificador="C">
        <!-- <datos_comun> -->
            <nombre>Pedro</nombre>
        <!-- Formato 3 letras, 4 numeros, 1 simoblo -->
            <codigo>Mss0002#$</codigo>
            <fecha>2022-05-18</fecha>
            <!-- </datos_comun> -->
        <apellidos>
            <!-- solo podemos elegir entre el primer apellido o el segundo  -->
            <primerapellido>Snchaez</primerapellido>
            <!-- <segundoapellido>Pérez</segundoapellido> -->
        </apellidos>
        <!-- restringimimos la edad entre los 18 años a los 100 años y solo valores posistivos-->
        <edad>18</edad>
        <email>perdsdaas@gmail.com</email>
        <telefono>(+044)994574122</telefono>
        <direccion>calle sin número </direccion>
    </cliente>
    <cliente identificador="D">
        <!-- <datos_comun> -->
            <nombre>Maribel</nombre>
        <!-- Formato 3 letras, 4 numeros, 1 simoblo -->
            <codigo>asL0004%$</codigo>
            <fecha>2022-05-11</fecha>
        <!-- </datos_comun> -->
        <apellidos>
            <!-- solo podemos elegir entre el primer apellido o el segundo  -->
            <!-- <primerapellido>Snchaez</primerapellido> -->
            <segundoapellido>Pérez</segundoapellido>
        </apellidos>
        <!-- restringimimos la edad entre los 18 años a los 100 años y solo valores posistivos-->
        <edad>23</edad>
        <email>Ejempl12@gmail.com</email>
        <telefono>(+593)075326591</telefono>
        <direccion>calle sin número</direccion>
    </cliente>
</clientes>
</biblioteca>
</tienda>
